stages:
  - build
  - deploy
  - cleanup

# Сборка веток и тегов
Build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH
  trigger:
    strategy: depend
    include:
      - local: '.gitlab-ci/variables/_Dev_Variables.yml'
      - local: '.gitlab-ci/_BuildRelease.yml'

# Деплой мастер ветки на DEV (автоматический)
DEV Deploy:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
      when: manual
  trigger:
    strategy: depend
    include:
      - local: '.gitlab-ci/variables/_Dev_Variables.yml'
      - local: '.gitlab-ci/_DeployRelease.yml'
  needs: ["Build"]

# Деплой тега на DEV (ручной)
DEV Release Deploy:
  stage: deploy
  only:
    - tags
  when: manual
  trigger:
    strategy: depend
    include:
      - local: '.gitlab-ci/variables/_Dev_Variables.yml'
      - local: '.gitlab-ci/_DeployRelease.yml'
  needs: ["Build"]

# Очистка репозитория
Cleanup:
  stage: cleanup
  trigger:
    include: '.gitlab-ci/_Cleanup.yml'
  only: [schedules]

