stages:
  - cleanup

# Инициализация Werf
.werf_init:
  image: registry.werf.io/werf/werf:1.2-rock-solid
  before_script:
    - source $(werf ci-env gitlab --as-file)
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - git config --global --add safe.directory '*'

# Очистка репозитория от устаревших контейнеров
Cleanup:
  extends: .werf_init
  stage: cleanup
  script:
    - werf cleanup --without-kube