apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Chart.Name }}-headers-middleware
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    sslRedirect: true
    accessControlMaxAge: 12
    addVaryHeader: true
    accessControlAllowCredentials: true
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "PATCH"
      - "POST"
      - "DELETE"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "*"
    customResponseHeaders: |
      Cache-Control: no-cache, no-store, must-revalidate

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Chart.Name }}-buffering-middleware
  namespace: {{ .Release.Namespace }}
spec:
  buffering:
    maxRequestBodyBytes: 1000000000

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: "{{ .Chart.Name }}-letsencrypt"
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Chart.Name }}-headers-middleware@kubernetescrd, {{ .Release.Namespace }}-{{ .Chart.Name }}-buffering-middleware@kubernetescrd
spec:
  tls:
    - hosts:
        - {{ .Values.external.DOMAIN }}
      secretName: {{ .Chart.Name }}-ingress-tls
  rules:
    - host: {{ .Values.external.DOMAIN }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Chart.Name }}-service
              servicePort: 3000