# Настройка приложения
debug: false
environment: production
token_refresh_timeout: 60

envExternalVariableCodes:
  - ENVIRONMENT
  - GRAPHQL_SERVER
  - GRAPHQL_WS_SERVER
  - SSR_GRAPHQL_SERVER
  - SSR_GRAPHQL_WS_SERVER
  - DEBUG
  - TOKEN_REFRESH_TIMEOUT
  - DOMAIN
  - MAIN_DOMAIN

